---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: realtimeapp-prd
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: realtime-prd
    namespace: realtime-prd
  - kind: Deployment
    name: redis-prd
    namespace: realtime-prd
  interval: 1m0s
  path: ./deploy/overlays/prd
  prune: true
  sourceRef:
    kind: GitRepository
    name: realtimeapp-infra
  timeout: 2m0s
  validation: client

